apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/deployment.yaml
- resources/service.yaml
images:
- name: api
  newName: docker.pkg.github.com/driesbierens/repairs-service/package
  newTag: 2e53b65c180a4a219e86c6c5653004bedce01628
