apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/deployment.yaml
- resources/service.yaml
images:
- name: api
  newName: docker.pkg.github.com/driesbierens/repairs-service/package
  newTag: b2c3d4462dc4f0e1d8f49cee893ed265c00f9d9b
