apiVersion: apps/v1
kind: Deployment
metadata:
  name: repairs-service
spec:
  selector:
    matchLabels:
      app: repairs-service
  template:
    metadata:
      labels:
        app: repairs-service
    spec:
      imagePullSecrets:
        - name: github-image-puller
      containers:
        - name: repairs-service
          image: api
          env:
            - name: MONGODB_HOST
              value: mongodb.default.svc.cluster.local
            - name: MONGODB_PORT
              value: '27017'
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "100m"

          ports:
            - containerPort: 8052