name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Login to Github Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u driesbierens --password-stdin docker.pkg.github.com
        
      - name: Build the Docker image
        run: docker build . --file .ci/build/Dockerfile --tag docker.pkg.github.com/driesbierens/repairs-service/package:${{ github.sha }}
        
      - name: Push docker image
        run: docker push docker.pkg.github.com/driesbierens/repairs-service/package:${{ github.sha }}
      
      - name: Logout from Github Packages
        run: docker logout docker.pkg.github.com
