name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.ci/**'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.ci/**'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Login to Docker
        run: docker login -u dbierens -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build the Docker image
        run: docker build . --file .ci/build/Dockerfile --tag dbierens/repairs-service:latest .
        
      - name: Push docker image
        run: docker push dbierens/repairs-service:latest
      
      - name: Logout from Github Packages
        run: docker logout
    
  update-image-name:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Update image name for kustomization
        run: cd .ci/deploy/k8s/base && docker run --rm --entrypoint /app/kustomize --workdir /app/src -v $(pwd):/app/src k8s.gcr.io/kustomize/kustomize:v3.8.7 edit set image api=docker.pkg.github.com/driesbierens/repairs-service/package:${{ github.sha }} && cd ../../../..

      - name: configure git user
        run: git config user.email '<>' && git config user.name "CI - Github Actions"

      - name: Commit changes
        run: git add .ci/deploy/k8s/base/kustomization.yaml && git commit -m "[ci] Update image to docker.pkg.github.com/driesbierens/repairs-service/package:${{ github.sha }}"
      
      - name: Push changes to master
        run: git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git master
