name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.ci/**'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.ci/**'
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -f pom.xml clean compile
  build:

    runs-on: ubuntu-latest
    needs: compile
    name: Java 11 build, deliver artifact and container
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Start MongoDB for integration test
        uses: supercharge/mongodb-github-action@1.3.0
        with:
         mongodb-version: 4.2

      - name: Test and build project
        run: mvn -f pom.xml clean install

      - name: Show contents of the current working directory
        run: ls -la

      - name: Show contents of the target directory
        run: ls -la target

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: repairs-service-artifact.jar
          path: ../target/repairs-service-0.0.1-SNAPSHOT.jar

      - name: Login to Docker
        run: docker login -u dbierens -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build the Docker image
        run: docker build -t dbierens/repairs-service:latest .
        
      - name: Push docker image
        run: docker push dbierens/repairs-service:latest
      
      - name: Logout from Docker
        run: docker logout
    
  update-image-name:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Update image name for kustomization
        run: cd .ci/deploy/k8s/base && docker run --rm --entrypoint /app/kustomize --workdir /app/src -v $(pwd):/app/src k8s.gcr.io/kustomize/kustomize:v3.8.7 edit set image api=docker.pkg.github.com/driesbierens/repairs-service/package:${{ github.sha }} && cd ../../../..

      - name: configure git user
        run: git config user.email '<>' && git config user.name "CI - Github Actions"

      - name: Commit changes
        run: git add .ci/deploy/k8s/base/kustomization.yaml && git commit -m "[ci] Update image to docker.pkg.github.com/driesbierens/repairs-service/package:${{ github.sha }}"
      
      - name: Push changes to master
        run: git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git master
